name: Start Digital Main
favicon: null
layout_spectrum: 0.49354
typography_spectrum: 0.50349
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#15161d'
    - '#cd273d'
    - '#fea15b'
    - '#858587'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
