name: Start Digital Main
favicon: null
layout_spectrum: 0.8985
typography_spectrum: 0.05225283862091601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#15161d'
    - '#cd273d'
    - '#fea15b'
    - '#858587'
  brandStrength: 1
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 1
purpose: []
